services:
  php:
    build: 
      context: ..
      dockerfile: docker/php/Dockerfile.php
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ../app:/var/www/html
    networks:
      - ${PROJECT_NAME}

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
    - "${APP_PORT}:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ${PROJECT_NAME}
      
  db:
    image: postgres
    container_name: ${PROJECT_NAME}_db
    ports:
      - "${DB_PORT}:5432"
    networks:
      - ${PROJECT_NAME}

networks:
  DockerTask:
    driver: bridge
